### ISSUE TITLE
All tests failing + res[1][1][0] is out of bounds of the array

### ISSUE THREAD

**Issue by fatcuntroller** [UnknownMemory/ggst-api#1]
Hey,
I really like the work done here, but I'm consistently getting Fails and Errors on the test suite. Regardless of what I use as SteamID the outcome is the same: the array is too small and does not contain username. Am I doing something wrong or was the API updated and code is now outdated?

**Comment by UnknownMemory** [comment]
Did you put the right hexadecimal of your Steam ID?
If you're playing on playstation i made a mistake the login method doesn't work with playstation account

**Comment by fatcuntroller** [comment]
Hello, no I'm on PC, I figured it out by checking ggst-api-rs, you need SteamID64 and it's hexadecimal, not SteamID, I thought the code was outdated because the Strive API didn't return anything significant. Thanks for the response though.
