### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by anthonydelle** [UnknownMemory/ggst-api#4]
I've tried to use this to no avail.  I have not gotten any of the functions to work.  Just wanted to make sure something wasn't changed on the Strive server side that made this not work anymore.

**Comment by UnknownMemory** [comment]
I updated it but the login function doesn't work for some reason. The other functions should work if you know your Strive ID

**Comment by anthonydelle** [comment]
Yes it seems logging in has changed since you first made this and does not work. Even knowing my StriveID it still does not work.  It seems to be because of this:
```python
def _msgpacking(self, body: list):
        req: list = []

        header: list = [
            self.player_id if self.player_id is not None else "",
            self.token if self.token is not None else "",
            6,
            VERSION,
            self.platform,
        ]

        req.append(header)
        req.append(body)
        message_pack = msgpack.packb(req).hex()

        return message_pack
```

the player id should not be in the header I believe. Changing to this will made get_rcode work correctly

```python
def _msgpacking(self, body: list):
        req: list = []

        header: list = [
             "",
            self.token if self.token is not None else "",
            6,
            VERSION,
            self.platform,
        ]

        req.append(header)
        req.append(body)
        message_pack = msgpack.packb(req).hex()

        return message_pack
``` 

I am new to github but I think i sent a pull request with the necessary  change.
#6

**Comment by UnknownMemory** [comment]
The ID is necessary for the other functions and everything works for me beside the login but it's indeed not necessary for the rcode

**Comment by anthonydelle** [comment]
Ok then I'll see if I can cancel the pull request I made
