### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by matteoiacovitti** [UnknownMemory/ggst-api#8]
Hello. 

I was wondering after your latest update (0.0.6) if you have any updated documentation?

I like what your doing with the GGST API and wanted to test it myself. 

I have a fun project I wanted to try out and was trying to do all this using cURL but to no avail. 

Thanks.

**Comment by UnknownMemory** [comment]
It's updated.
The new login method requires you to use your steam account if you play on steam. I'll try to add the xbox and playstation login later.

They changed the ranking endpoints, the methods doesn't work for the moment.
